version: "3.9"
services:
    db:
        image: postgres:14.5-alpine
        restart: always
        environment:
            - POSTGRES_USER=vasuphol1997
            - POSTGRES_PASSWORD=a4nxXsJPV3Re
        ports:
            - "5433:5433"
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
